### PR TITLE
Add support for defrec to have docstring and be private

### PR DESCRIPTION
**Pull request by enforser**
These changes allow `defrec` to (optionally) be defined with a docstring: 
```
(defrec foo 
  "this is a docstring"
  [x]
  (when x x))

(:doc (meta #'foo)) ;; => "this is a docstring" 
```
They also add a new macro which makes the functions private: `defrec-`
```
(defrec- foo [x] x)
```

```
Ran 4 tests containing 10 assertions.
0 failures, 0 errors.
```

### CODE REVIEW

**Comment by divs1210** [comment]
Hi, @enforser!
Thank you for the PR! These certainly are useful features.
I will also add a TODO somewhere in the repo soon.
I see this fixes both https://github.com/divs1210/xodarap/issues/1 and https://github.com/divs1210/xodarap/issues/2.

**Comment by enforser** [comment]
I'm glad you think that these features are useful! I was originally just going to raise the issues, but started playing around with it and ended up with a solution so thought I might as well put up a PR. 

Feel free to leave any review comments on the PR and I will get to fixing them up. Otherwise, feel free to merge at your own discretion!

**Comment by divs1210** [comment]
@enforser Hi! I would like you to make a few changes:
- Move docstring from `defrec*` -> `defrec`
- I don't think adding `defrec-` is a good idea - `(defrec ^:private ...)` works just fine

Thanks!

**Comment by divs1210** [comment]
@enforser hi!
please pull and rebase against this repo.
the PR automatically got closed because I was fiddling with the git history.

**Comment by enforser** [comment]
@divs1210 When I have some time I'll update based off your suggestions then put up a PR again. Thanks!

**Pull request closed without merging**
